[platformio]
default_envs = waveshare_43b

[env:waveshare_43b]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
    platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
    platformio/framework-arduinoespressif32-libs@https://dl.espressif.com/AE/esp-arduino-libs/esp32-3.1.1-h.zip
board = BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_4_3_B
monitor_speed = 115200
lib_deps =
    https://github.com/h2zero/NimBLE-Arduino.git#d94442358aa8f6e4aaac9b4c4650fb49d7ee27c7
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#92b790ed6d24b0678e2f45b1fc85f0abd2d41b33
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
    https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
    https://github.com/lvgl/lvgl.git#v8.4.0
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -I src
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_4_3_B
    -DLV_COLOR_16_SWAP=0

[env:jc4827w543_smoke]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
    platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
    platformio/framework-arduinoespressif32-libs@https://dl.espressif.com/AE/esp-arduino-libs/esp32-3.1.1-h.zip
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default.csv
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
build_src_filter =
    +<jc4827w543_smoke.cpp>
lib_deps =
    https://github.com/moononournation/Arduino_GFX.git
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DESP32_4827S043
